#!/bin/bash
#
#algus
#
echo -n "Sisestage oma vanus:"
read v

if [ $v -ge 0 -a $v -le 11 ] #vanus on vahemikus 0-11
then
	echo "Oled laps!"

elif [ $v -ge 11 -a $v -le 18 ] #vanus on vahemikus 11-18
then
	echo "Oled nooruk" 

elif [ $v -ge 18 -a $v -le 63 ] #vanus on vahemikus 18-63
then
	echo "Oled täiskasvanu"

elif [ $v -ge 63 ]
then
	echo "Oled senjoor"
else
	echo "Vigane sisend"
fi
