#!/bin/bash
#
# Tsüklid 3
#
echo -n "Sisestage ridade arv: "
read rida
echo -n "Sisestage tärnide arv: "
read tarn
for (( i = 1; i <= $rida; i++ ))
do
	echo -n "$i "
	# Kui on esimene või viimane rida
	if [ $i -eq 1 -o $i -eq $rida ]; then
	# Rida tärnidest
	for (( j = 1; j <= $tarn; j++ ))
	do
	 echo -n "* "
	done
	# Teine rida
	else
	 echo -n "* "
	# Tühik
	for (( j = 2; j < $tarn; j++ ))
	do
	 echo -n "  "
	done
	echo -n "* "
	fi
	echo
done

