#!/bin/bash
#
# Tsüklid 4
for (( i = 1; i <= 1; i++ ))
do
	echo -n "$i "
	for (( j = 1; j <= 1; j++ ))
	do
	echo -n "* "
	done
	echo "" #### Print the new line ###
done
for (( i = 2; i <= 2; i++ ))
do
	echo -n "$i "
	for (( j = 2; j <= 3; j++ ))
	do
	echo -n "* "
	done
	echo "" #### print the new line ###
done
for (( i = 3; i <= 3; i++ ))
do
	echo -n "$i "
	for (( j = 3; j <= 5; j++ ))
	do
	echo -n "* "
	done
	echo "" #### print the new line ###
done
for (( i = 4; i <= 4; i++ ))
do
	echo -n "$i "
	for (( j = 4; j <= 7; j++ )) 
	do
	echo -n "* "
	done
	echo "" #### print the new line ###
done 
for (( i = 5; i <= 5; i++ ))
do
	echo -n "$i "
	for (( j = 5; j <= 9; j++ ))
	do
	echo -n "* "
	done
	echo ""
done
  
