#!/bin/bash
#
# Tsüklid 5

for ((r = 4; r >= 1; r-- ))
do


        for ((i = 1; i >= 5; i--))
        do
                echo -n "$i "
        done

	for((o=1; o<=$r; o++))
	do
  		echo -n "o "
	done

	for((t=1; t<=(5-$r); t++))
        do
                echo -n "* "
        done

	echo
done
